version: "3"

services:
  database:
    image: mysql
    container_name: skkuchin-db
    environment:
      - MYSQL_DATABASE=service
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
        - 3306:3306
    # db 데이터 유지하고 싶을 때 밑의 2줄 주석 풀기    
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
        - skkuchin-network

  server:
    build:
        context: "./backend"
        dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    container_name: skkuchin-backend
    environment:
      - LANGUAGE=ko_KR.UTF-8
      - LANG=ko_KR.UTF-8
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    volumes:
      - ./backend:/app
    working_dir: /app
    networks:
      - skkuchin-network

  client:
    build:
        context: "./frontend"
        dockerfile: Dockerfile 
    restart: always
    container_name: skkuchin-frontend
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - NODE_ENV=prod
      - NEXT_PUBLIC_API_URL=http://server:8080
      - NEXT_PUBLIC_KAKAOMAP_APPKEY=0d8f0e65047ebb4fce295a83614d7fae
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - skkuchin-network

networks:
  skkuchin-network: