version: "3"

services:
  server:
    image: server
    build:
      context: "./backend"
      dockerfile: Dockerfile
  client:
    image: client
    build:
      context: "./frontend"
      dockerfile: Dockerfile.prod
  nginx:
    image: nginx:1.13.9-alpine
    build:
      context: "./nginx"
      dockerfile: Dockerfile