version: "3"

services:
  server:
    image: server
    build:
      context: "./backend"
      dockerfile: Dockerfile.prod
  client:
    image: client
    build:
      context: "./frontend"
      dockerfile: Dockerfile.prod
  nginx:
    image: nginx
    build:
      context: "./nginx"
      dockerfile: Dockerfile
  redis:
    image: redis
    build:
      context: "./redis"
      dockerfile: Dockerfile