name: Build and Push Docker Image
on:
  push:
    branches:
      - prod
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::659575527594:role/my-github-actions-role
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: skkuchin-repo
          IMAGE_TAG: latest
        run: |
          docker-compose -f docker-compose.prod.yml build server nginx
          docker tag server:latest $REGISTRY/$REPOSITORY:server-$IMAGE_TAG
          docker tag nginx:latest $REGISTRY/$REPOSITORY:nginx-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:server-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:nginx-$IMAGE_TAG

      - name: npm build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Upload /deploy to S3
        env:
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME}}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 frontend/build s3://$BUCKET_NAME
