name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::659575527594:role/my-github-actions-role
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          docker pull nginx
          docker tag nginx:latest 659575527594.dkr.ecr.ap-northeast-2.amazonaws.com/nginx:latest
          docker push 659575527594.dkr.ecr.ap-northeast-2.amazonaws.com/nginx:latest
