name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::659575527594:role/my-github-actions-role
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: skkuchin-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker-compose build
          docker tag skkuchin-server:latest $REGISTRY/$REPOSITORY:server-$IMAGE_TAG
          docker tag skkuchin-client:latest $REGISTRY/$REPOSITORY:client-$IMAGE_TAG
          docker tag skkuchin-database:latest $REGISTRY/$REPOSITORY:database-$IMAGE_TAG
          docker tag skkuchin-rabbitmq:latest $REGISTRY/$REPOSITORY:rabbitmq-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:server-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:client-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:database-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:rabbitmq-$IMAGE_TAG
