name: Build, Push Docker Image and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::659575527594:role/my-github-actions-role
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update frontend config
        run: |
          sed -i 's|export const API_URL = process.env.NEXT_PUBLIC_API_URL;|export const API_URL = "https://www.skkuchin.com";|' frontend/src/config/index.js
          sed -i 's|export const KAKAOMAP_APPKEY = process.env.NEXT_PUBLIC_KAKAOMAP_APPKEY;|export const KAKAOMAP_APPKEY = "0d8f0e65047ebb4fce295a83614d7fae";|' frontend/src/config/index.js
          sed -i 's|export const WEB_PUSH_PUBLIC_KEY = process.env.NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY;|export const WEB_PUSH_PUBLIC_KEY = "BJkNh3LjryGnKrmWZCY_fAebZqGPhtuzBZCBBoB7lPh54M1raOJGfATpy0X7BpVahZJXk6Iq6XFTxM4STBMSFTY";|' frontend/src/config/index.js

      - name: Copy prod ServiceApplication.java file
        run: |
          cp prod/ServiceApplication.java backend/src/main/java/skkuchin/service/

      - name: Build backend
        working-directory: ./backend
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: skkuchin-repo
          IMAGE_TAG: latest
        run: |
          docker-compose -f docker-compose.prod.yml build server client nginx redis
          docker tag server:latest $REGISTRY/$REPOSITORY:server-$IMAGE_TAG
          docker tag client:latest $REGISTRY/$REPOSITORY:client-$IMAGE_TAG
          docker tag nginx:latest $REGISTRY/$REPOSITORY:nginx-$IMAGE_TAG
          docker tag redis:latest $REGISTRY/$REPOSITORY:redis-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:server-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:client-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:nginx-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:redis-$IMAGE_TAG
